#!/bin/bash
#------------------------------
#-- test runner
#------------------------------

# exit with an error, if any internal script errors
set -e



# run Nightwatch test scripts against local Meteor
./nightwatch.js --config nightwatch.json --test test/e2e/spec.js


