#!/bin/bash
#------------------------------
#-- test runner
#------------------------------

# exit with an error, if any internal script errors
set -e


kill `lsof -t -i:4444`
selenium &
# run Nightwatch test scripts against
./nightwatch.js --config nightwatch.json --test tests/e2e/spec.js


